// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zojmtriygejkfakanjtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvam10cml5Z2Vqa2Zha2FuanR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDc1MTksImV4cCI6MjA2NDAyMzUxOX0.w4J5VAP4YFS40oZOPZ8H5yqK5JfUAM-4G4FxxEEWc2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);